name: tree-walker
version: 0.1.0.0
github: "Quaqqer/crafting-interpreters/tree-walker"
author: "Emanuel S"
maintainer: "emanuel@empa.xyz"

description: Please see the README on GitHub at <https://github.com/Quaqqer/crafting-interpreters/tree/master/tree-walker#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions: [
    OverloadedStrings,
    DisambiguateRecordFields,
    DuplicateRecordFields,
    LambdaCase,
    MultiWayIf,
    NamedFieldPuns,
    RecordWildCards,
    TupleSections,
    ViewPatterns,
    # OverloadedRecordDot,
  ]

library:
  source-dirs: src

executables:
  tree-walker-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tree-walker

tests:
  tree-walker-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tree-walker
