name: htreelox
version: 0.1.0.0
github: "Quaqqer/crafting-interpreters/tree-walker"
author: "Emanuel S"
maintainer: "emanuel@empa.xyz"

description: Please see the README on GitHub at <https://github.com/Quaqqer/crafting-interpreters/tree/master/tree-walker#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - optparse-applicative

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wno-name-shadowing

default-extensions:
  [
    OverloadedStrings,
    DisambiguateRecordFields,
    DuplicateRecordFields,
    LambdaCase,
    MultiWayIf,
    NamedFieldPuns,
    RecordWildCards,
    TupleSections,
    ViewPatterns,
    OverloadedRecordDot,
    NoFieldSelectors,
    ScopedTypeVariables,
    FlexibleContexts,
    FlexibleInstances,
    ImportQualifiedPost,
  ]

library:
  source-dirs: src

executables:
  htreelox:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - htreelox

tests:
  htreelox-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - htreelox
